### ISSUE TITLE
using AWS SSO via Okta Idp

### ISSUE THREAD

**Issue by vhoanguyen** [ryansonshine/aws-sso-creds-helper#1]
aws2 --profile AdministratorAccess-900359709859 sso login
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.ap-southeast-2.amazonaws.com/

Then enter the code:

XXXXX-XXXX
Successully logged into Start URL: https://d-3131231.awsapps.com/start
Vans-MacBook-Air:bin vhoanguyen$ ssocreds -p AdministratorAccess-03485092385
[aws-sso-creds-helper]: Getting SSO credentials for profile AdministratorAccess-03485092385
[aws-sso-creds-helper]: Failed to load SSO credentials for profile AdministratorAccess-03485092385
[aws-sso-creds-helper]: Cached SSO login is expired/invalid, try running `aws sso login` and try again

**Comment by ryansonshine** [comment]
Hi @vhoanguyen, I'm investigating this issue now; do you have your `sso_region` set in your sso config?

**Comment by vhoanguyen** [comment]
I had it, but it will work fine if i run like this "AWS_DEFAULT_PROFILE=ap-southeast-2 ssocreds -p AdministratorAccess-03485092385".

thanks

**Comment by ryansonshine** [comment]
Ah yes, sounds good. If you're using multiple profiles I recommend checking out something like https://github.com/antonbabenko/awsp

This essentially sets the `AWS_DEFAULT_PROFILE` on each switch.
