### ISSUE TITLE
respect AWS_SHARED_CREDENTIALS_FILE var

### ISSUE THREAD

**Issue by stobias123** [ryansonshine/aws-sso-creds-helper#12]
Love the tool, minor feature request.

I use
```shell
export AWS_SHARED_CREDENTIALS_FILE=foobar
```
to segregate creds files for multiple environments. 

Any chance you could add a feature to respect this var instead of only writing to the default aws location?

**Comment by ryansonshine** [comment]
Good idea! I'll take a look this evening

**Comment by ryansonshine** [comment]
#13 Merged and published
