### ISSUE TITLE
Retain the credential file comments

### ISSUE THREAD

**Issue by esiva** [ryansonshine/aws-sso-creds-helper#16]
Can the comments in credentials file retained when refreshing the credentials. Right now all comments are removed.

**Comment by ryansonshine** [comment]
Thanks for the suggestion @esiva ! I'll take a look into this soon

**Comment by ryansonshine** [comment]
Hey @esiva , it appears the core library used for parsing ini files doesn't support preserving comments. There was a feature request put out back in 2014 (https://github.com/npm/ini/issues/32) that doesn't look like it'll be going in anytime soon. 

I don't see any comparable libraries mature enough I'd feel comfortable using to accomodate this request. Closing for now but if anyone has any recommendations I'd be open to hearing them
