### ISSUE TITLE
Unnecessarily fails if the ~/.aws/sso/cache folder doesn't exist

### ISSUE THREAD

**Issue by chill389cc** [ryansonshine/aws-sso-creds-helper#64]
## Current Behavior

When users of this app initially install the app, often their `~/.aws` folder is nonexistent or empty. Of course the `config` file is required, but even when that is supplied, the app fails until they make an empty `sso` folder in it and then put a `cache` folder inside that sso folder.Neither folder needs to contain anything (except for /sso containing /cache), but that folder structure needs to exist for `ssocreds` to run successfully.

## Expected Behavior

The desired behavior would be to do the following: 
- if this folder structure is detected to not exist when it as attempted to be read, create it
  - this is fine since the program works just fine when the folders are empty, so creating them as empty folders programmatically should be no problem

## Steps to Reproduce the Problem

  1. Delete your `~/.aws/sso` folder
  1. Attempt to run `ssocreds`
  1. Notice the error message that appears: `ENOENT: no such file or directory, scandir 'C:\Users\john\.aws\sso\cache`

## Environment

- Version: Many versions,  including the most recent one: 1.10.1
- Platform: Windows
- Node.js Version: bug reported on 16 and 18

When I have time I'd be happy to make PR fixing this, but that won't be for a couple days, so I wanted to report this issue to remind myself.

**Comment by ryansonshine** [comment]
Thanks for the detailed report! I'll get a fix out for this by EOD.

**Comment by ryansonshine** [comment]
@all-contributors please add @chill389cc for bugs
