### ISSUE TITLE
Optional flag to set AWS_PROFILE when run

### ISSUE THREAD

**Issue by chill389cc** [ryansonshine/aws-sso-creds-helper#67]
## Feature Request

**Is your feature request related to a problem? Please describe.**
No, just different functionality of the aws cli.

**Describe the solution you'd like**
setting the AWS_PROFILE environment variable locally in the shell when run to the account that is specified when the -p flag is used.

**Describe alternatives you've considered**
I often run ssocreds thinking that I will be ready to use whatever aws cli app or tool I am wanting to use, but sometimes it still fails because AWS_PROFILE is not set to the right account, despite having run  ssocreds  for the correct account. When I realize this is the case, I manually have to run `export AWS_PROFILE=the account I want`, or the equivalent for whatever shell I'm in. 

I've considered forking this repo and adding that feature myself, but I'd rather not have to solely maintain my own fork...

## Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.
Not sure exactly when I'll find the time but I can probably pull this together, especially because there is no rush.

Maybe I'm a fool for submitting this feature and maybe it shows that I completely misunderstand the AWS CLI and related topics. If so, I'm willing to accept that haha. I'm new to all of this, but in my specific use case, it seems like a feature like this would be useful. Any comments? If no one says anything I think I'd like to start working on this sometime soon. Working on CLI apps is fun.

**Comment by ryansonshine** [comment]
I think this would be a great addition, PR welcome!

**Comment by chill389cc** [comment]
School just started and its a heavier workload than I anticipated. I've still got this on my todo list but It's lower on the priority right now. I'll get to it eventually!

**Comment by ryansonshine** [comment]
> School just started and its a heavier workload than I anticipated. I've still got this on my todo list but It's lower on the priority right now. I'll get to it eventually!

No worries! We all have our day jobs to tend to :smile:

**Comment by chill389cc** [comment]
Unfortunately it looks like this feature is basically impossible by design of modern shells. Setting the environment of the parent shell from a child process is very difficult/annoying for shell scripts, and seemingly impossible from a node app.

If curious, read [here](https://stackoverflow.com/a/496777/6901706). I read a lot of other comments and pages that say the same thing. There are workarounds, but those are not really compatible with how a globally installed npm module running as a CLI app works.

This is a bummer, but makes sense. I'll just keep using the shell-specific `export` command after running `ssocreds` when the opportunity calls for it 🥲.
